# Generated by Django 2.1.1 on 2019-03-25 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, verbose_name='Codigo expediente')),
                ('tipo', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('LABORAL', 'Laboral'), ('PENAL', 'Penal'), ('CIVIL', 'Civil'), ('ADMINISTRATIVO', 'Administrativo'), ('CONSTITUCIONAL', 'Constitucional')], default='LABORAL', max_length=50, verbose_name='Tipo Expediente')),
                ('numero_folio', models.SmallIntegerField(default=0, verbose_name='Numero de folios')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['codigo', 'created', 'updated'],
            },
        ),
    ]
