# Generated by Django 2.1.1 on 2019-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20190325_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='descripcion',
            field=models.TextField(default='modificar', verbose_name='Descripcion'),
        ),
    ]
