# Generated by Django 2.1.1 on 2019-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_expediente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='flag',
            field=models.BooleanField(blank=True, null=True, verbose_name='Revision'),
        ),
    ]
